export const projects = [
    {
        id: "todoapp",
        title: "Todo App",
        subtitle: "TS 활용 TodoApp 토이프로젝트",
        date: "2025. 11",
        description: [
            "타입스크립트 숙련을 위한 TodoList 미니 프로젝트입니다.",
            "TypeScript와 Framer-Motion을 활용해 제작하였습니다.",
        ],
        features: "Framer-Motion 활용 드래그&드롭, 로컬스토리지 저장",
        skills: ["Typescript", "Vite", "Tailwind", "Node.js"],
        slides: [
            "./portfolio/page1.jpg",
            "./portfolio/page2.jpg",
            "./portfolio/page3.jpg",
        ],
        github: "https://github.com/Jonggu-code/TodoApp",
        link: "https://todo-app-xi-peach.vercel.app/",
        modal: "todoapp",
    },
    {
        id: "portfolio",
        title: "Portfolio",
        subtitle: "개인용 포트폴리오 사이트",
        date: "2025. 01",
        totalDate: "2025. 01. 03 ~ 개발 진행 중",
        description: [
            "이력서와 함께 나의 역량과 강점 그리고 개인 프로젝트들을 한눈에 볼 수 있도록 제작했습니다.",
            "React와 Tailwind를 활용했고, 컴포넌트 관계성과 Hooks 숙련도가 상승했습니다.",
        ],
        features: "스크롤 반응형, 다크모드",
    },
    {
        id: "matmap",
        title: "MatMap - 맛맵",
        subtitle: "유저 맞춤형 맛집 검색 지도",
        date: "2024. 11",
        description: [
            "사람들이 맛집을 검색함에 있어 가장 원하는 정보, 정제된 정보를 전달해주는 사이트를 제작했습니다.",
            "팀 프로젝트를 진행하며 <strong>협업과 소통의 중요성</strong>을 느꼈고 <strong>데이터 크롤링, 카카오맵 API 활용</strong>을 경험했습니다.",
        ],
        features: "반응형 웹페이지, 카카오맵 API 활용, 카테고리별 맛집 검색",
        skills: ["HTML", "CSS", "Javascript", "JQuery"],
        slides: [
            "./Matmap/index.png",
            "./Matmap/detail.jpg",
            "./Matmap/detail2.jpg",
            "./Matmap/rankpage.png",
            "./Matmap/mypage.png",
            "./Matmap/review.png",
        ],
        github: "https://github.com/Jonggu-code/MatMap_portfolio",
        link: "https://jonggu-code.github.io/MatMap_portfolio/HTML,CSS,JS/index.html",
    },
    {
        id: "youtube",
        title: "Youtube Music Reworks",
        subtitle: "유튜브 뮤직 리워크 프로젝트",
        date: "2024. 10",
        description: [
            "유튜브 뮤직 클론 코딩을 진행습니다. UI/UX 적으로 개선되면 좋을 것 같다고 생각한 부분을 개선해 봤습니다.",
            "<strong>Javascript, jquery의 코드 숙련도가 상승하였고, 미디어 제어, 반응형 웹페이지</strong> 제작 방법에 대한 공부가 되었습니다.",
        ],
        features: "반응형 웹페이지, 미디어 제어, 로컬스토리지 활용",
        skills: ["HTML", "CSS", "Javascript", "JQuery"],
        slides: [
            "./youtube/index.jpg",
            "./youtube/storage.jpg",
            "./youtube/playlist.jpg",
            "./youtube/playpage.jpg",
        ],
        github: "https://github.com/Jonggu-code/Portfolio_youtube",
        link: "https://jonggu-code.github.io/Portfolio_youtube/246.%ED%8F%AC%ED%8A%B8%ED%8F%B4%EB%A6%AC%EC%98%A41(%EC%9C%A0%ED%8A%9C%EB%B8%8C).html",
    },
];
